# Generated by Django 3.2.8 on 2021-10-11 12:11

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.CharField(choices=[('START', 'start'), ('STOP', 'stop'), ('REPORT', 'report')], max_length=10, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('program_time', models.TimeField()),
                ('actual_time', models.DateTimeField(auto_now=True)),
                ('color', colorfield.fields.ColorField(blank=True, choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default=None, max_length=10, null=True)),
            ],
        ),
    ]
