# Generated by Django 3.2.8 on 2021-10-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsAPI', '0003_auto_20211013_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='color',
            field=models.CharField(default=(229, 255, 0, 0.801), max_length=30, null=True),
        ),
    ]
