# Generated by Django 3.2.8 on 2021-10-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsAPI', '0004_alter_tasks_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='color',
        ),
        migrations.AddField(
            model_name='tasks',
            name='clock_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='hourhand_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='wall_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
