# Generated by Django 3.2.8 on 2021-10-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsAPI', '0005_auto_20211016_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='clock_color',
            field=models.CharField(default='#9c7077', max_length=30),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='hourhand_color',
            field=models.CharField(default='#630ec4', max_length=30),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='wall_color',
            field=models.CharField(default='#500909', max_length=30),
        ),
    ]
